// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using System.Threading.Tasks;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace AdventureWorksEntities
{
    // DatabaseLog
    public class DatabaseLog
    {
        public int DatabaseLogId { get; set; } // DatabaseLogID (Primary key). Primary key for DatabaseLog records.
        public DateTime PostTime { get; set; } // PostTime. The date and time the DDL change occurred.
        public string DatabaseUser { get; set; } // DatabaseUser. The user who implemented the DDL change.
        public string Event { get; set; } // Event. The type of DDL statement that was executed.
        public string Schema { get; set; } // Schema. The schema to which the changed object belongs.
        public string Object { get; set; } // Object. The object that was changed by the DDL statment.
        public string Tsql { get; set; } // TSQL. The exact Transact-SQL statement that was executed.
        public string XmlEvent { get; set; } // XmlEvent. The raw XML data generated by database trigger.
    }

}
